wsgridderexample:	wspredictionexample.cpp ../wstackinggridder.cpp
	g++ -Wall -o wspredictionexample -I ../../external/aocommon/include/ -std=c++20 -DAVOID_CASACORE wspredictionexample.cpp ../wstackinggridder.cpp -lfftw3 -lfftw3f -lfftw3_threads -lfftw3f_threads
